name: CI

on:
  pull_request:

jobs:
  basic-checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: .tool-versions
          cache: npm

      - run: npm ci

      - name: Lint
        run: npm run biome

      - name: Build
        run: npm run build

      - name: Setup Playwright
        run: npx playwright install --with-deps

      - name: e2e-test
        run: npm run test:e2e
